services:
  openchronicle:
    build: .
    entrypoint: ["oc"]
    environment:
      - OC_DB_PATH=/data/openchronicle.db
      - OC_CONFIG_DIR=/config
      - OC_PLUGIN_DIR=/plugins
    env_file:
      - .env
    volumes:
      - "D:/Docker/openchronicle/data:/data"
      - "D:/Docker/openchronicle/config:/config"
      - "D:/Docker/openchronicle/plugins:/plugins"
